url: 'https://raw.githubusercontent.com/orien/puml-themes/main/themes/'
themes:
  - solarized-light
diagrams:
  - name: Sequence
    puml:
      - puml/sequence/participants.puml
      - puml/sequence/lifeline.puml
      - puml/sequence/notes.puml
      - puml/sequence/groups.puml
      - puml/sequence/participants-encompass.puml
      - puml/sequence/divider.puml
  - name: Class
    puml:
      - puml/class/basic-inheritance.puml
      - puml/class/interface-implementation.puml
      - puml/class/module-composition.puml
  - name: Activity
    puml:
      - puml/activity/basic-flow.puml
      - puml/activity/decision-merge.puml
      - puml/activity/swimlanes.puml
