@startuml
participant Alice
participant "The **Famous** Bob" as Bob

Alice -> Bob : hello --there--
... Some ~~long delay~~ ...
Bob -> Alice : ok
note left
  This is **bold**
  This is //italics//
  This is ""monospaced""
  This is --stroked--
  This is __underlined__
  This is ~~waved~~
end note

Alice -> Bob : A //well formatted// message
note right of Alice
 This is <size:18>displayed</size>
 __left of__ Alice.
end note
note left of Bob
 <u:#$RED>This</u> is <color #$BLUE>displayed</color>
 **<color:$MAGENTA>left of</color> <s:#$RED>Alice</strike> Bob**.
end note
note over Alice, Bob
 <w:#$MAGENTA>This is hosted</w> by <img:https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png{scale=0.1}>
end note
@enduml
